Add `sctring` to handle Linux environment
This line should be added because the following error has occured on the
Linux envrionment.

```
~/hakoniwa-bridge/virtual$ bash build.bash
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ZENOH_C_LIBRARY_PATH: /usr/local/lib/libzenohc.so
-- HAKO_C_LIBRARY: /usr/local/lib/hakoniwa/libassets.so
-- HAKO_CONDUCTOR_C_LIBRARY: /usr/local/lib/hakoniwa/libconductor.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/azureuser/hakoniwa-bridge/virtual/cmake-build
[ 25%] Building CXX object shm-proxy/CMakeFiles/shm-proxy.dir/src/shm_proxy.cpp.o
[ 50%] Building CXX object shm-proxy/CMakeFiles/shm-proxy.dir/src/shm_proxy_pdu.cpp.o
/home/azureuser/hakoniwa-bridge/virtual/shm-proxy/src/shm_proxy_pdu.cpp: In function 'void shm_proxy_pdu_data_handler(const z_sample_t*, void*)':
/home/azureuser/hakoniwa-bridge/virtual/shm-proxy/src/shm_proxy_pdu.cpp:22:13: error: 'memcpy' was not declared in this scope
   22 |             memcpy(writer.buffer.data.get(), sample->payload.start, sample->payload.len);
      |             ^~~~~~
/home/azureuser/hakoniwa-bridge/virtual/shm-proxy/src/shm_proxy_pdu.cpp:4:1: note: 'memcpy' is defined in header '<cstring>'; did you forget to '#include <cstring>'?
    3 | #include <iostream>
  +++ |+#include <cstring>
    4 |
make[2]: *** [shm-proxy/CMakeFiles/shm-proxy.dir/build.make:90: shm-proxy/CMakeFiles/shm-proxy.dir/src/shm_proxy_pdu.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:98: shm-proxy/CMakeFiles/shm-proxy.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```